{% set version = "0.33-dev" %}

package:
  name: larray
  version: {{ version }}

source:
  git_tag: {{ version }}
  git_url: https://github.com/larray-project/larray.git
#  git_tag: master
#  git_url: file://c:/Users/gdm/devel/larray/.git

build:
  # If this is a new build for the same version, increment the build number
  number: 0
  # we can use this instead of explicit build scripts (bld.bat and build.sh)
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - pip
    - python

  run:
    - python
    - numpy >=1.13
    - pandas >=0.20

test:
#  requires:
#    - pytest
#    - pytables

  imports:
    - larray

#  commands:
#    # You can also put a file called run_test.py in the recipe that will be run at test time.
#    - pytest --pyargs larray

about:
  home: http://github.com/larray-project/larray
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: "Labeled N-dimensional array."
  description: |
    LArray is open source Python library that aims to provide tools for
    easy exploration and manipulation of N-dimensional labelled data structures.
  doc_url: http://larray.readthedocs.io/
  dev_url: http://github.com/larray-project/larray

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen

# See
# https://conda.io/docs/user-guide/tasks/build-packages/index.html
# for more information about meta.yaml
