package:
  name: larray
  version: 0.26.1

source:
  git_tag: 0.26.1
  git_url: https://github.com/liam2/larray.git
#  git_tag: master
#  git_url: file://c:/Users/gdm/devel/larray/.git

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - pandas
    - pytest-runner

  run:
    - python
    - numpy >=1.10
    - pandas
    - pytest-runner

test:
#  requires:
#    - pytest
#    - pytest-runner

  imports:
    - larray

#  commands:
#    - pytest

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/liam2/larray
  license: GPL
  summary: "Labeled N-dimensional array."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
