{% set version = "0.34.4" %}

package:
  name: larray
  version: {{ version }}

source:
  git_tag: {{ version }}
  git_url: https://github.com/larray-project/larray.git

build:
  noarch: python
  # If this is a new build for the same version, increment the build number
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - numpy >=1.22
    - pandas >=0.20

test:
  requires:
    - pytest

  imports:
    - larray

  commands:
    - pytest --pyargs larray

about:
  home: http://github.com/larray-project/larray
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "N-dimensional labelled arrays in Python"
  description: |
    LArray is an open source Python library that aims to provide tools for
    easy exploration and manipulation of N-dimensional labelled data structures.
  doc_url: http://larray.readthedocs.io/
  dev_url: http://github.com/larray-project/larray

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
