New features
------------

* implemented LArray.expand to add dimensions
* implemented prepend
* implemented sort_axis
* allow creating 0d (scalar) LArrays

Miscellaneous improvements
--------------------------

* made extend expand its arguments
* made .append expand its value before appending
* changed read_* to not sort data by default
* more minor stuff :)

Fixes
-----

* fixed loading 1d arrays
