.. py:currentmodule:: larray


Syntax changes
^^^^^^^^^^^^^^

* renamed ``LArray.old_method_name()`` to :py:obj:`LArray.new_method_name()` (closes :issue:`1`).

* renamed ``old_argument_name`` argument of :py:obj:`LArray.method_name()` to ``new_argument_name``.


Backward incompatible changes
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* other backward incompatible changes


New features
^^^^^^^^^^^^

* added the :py:obj:`ExcelReport` class allowing to generate multiple graphs in an
  Excel file at once (closes :issue:`676`).


.. _misc:

Miscellaneous improvements
^^^^^^^^^^^^^^^^^^^^^^^^^^

* improved something.


Fixes
^^^^^

* fixed something (closes :issue:`1`).
