name: larray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy
  - pandas
  - matplotlib
  - pytables
  - jupyter
  - jupyter_client
  - sphinx
  - numpydoc
  - nbsphinx
  - pandoc
  - pip:
    - larray-editor
