name: larray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy
  - pandas
  - matplotlib
  - pytables
  - xlrd
  - openpyxl
  - sphinx
  - numpydoc
  - pandoc
  - ipython
  - ipykernel
  - nbsphinx
