.. py:currentmodule:: larray_editor

Miscellaneous improvements
^^^^^^^^^^^^^^^^^^^^^^^^^^

* display the filename and line number in the status bar when the editor is called from a Python script
  (closes :editor_issue:`173`).


Fixes
^^^^^

* fixed editor console unusable after any exception (closes :editor_issue:`166`).

* fixed LArray editor launcher in Windows menu (closes :editor_issue:`169`).
