name: Test LArray

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build-linux:
    # name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    name: Test on ${{ matrix.python-version }}
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - run: conda info
    - run: conda list
    - run: conda config --show
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - run: pytest
